nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
        skip_same_as_origin: true
    paths:
        '^/api/':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#            allow_headers: ['X-Custom-Auth', 'Content-type']
#            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            allow_headers: [ 'X-Custom-Auth', 'Content-Type', 'Authorization', 'Location' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE', 'OPTION' ]
            expose_headers: [ 'Link', 'Location' ]
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: ['Content-type']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
            hosts: ['^api\.']